.gitignore, .travis.yml, Cargo.toml, examples/rust_lang_tester/lang_tests/no_main.rs, examples/rust_lang_tester/lang_tests/unknown_var.rs, examples/rust_lang_tester/lang_tests/unused_var.rs, examples/rust_lang_tester/tester.rs, src/lib.rs, src/parser.rs, src/tester.rs
This is a heavy rewrite of the preview from a day or two back, though the external API is mostly unchanged. The good news is that this is powerful enough to deal with both Rust and SOM tests, and to do so requiring very little code from the user of the library.
What has changed significantly since you last saw things is the internal code and the format of the tests themselves. I moved from a custom parser to YAML, but that was horrible: multi-line, nested YAML simply doesn't work as I expect, and the Rust YAML parser gives confusing error messages. I've thus moved to TOML. Is this a good idea? I'm wondering if the best syntax would, regrettably, be a custom indentation (almost YAML, but not quite) one:
```
// Compiler:
//     status: success
//     stderr:
//         warning: unused …
```
=> First version of a lang tester

src/fuzzy.rs, src/lib.rs, src/parser.rs, src/tester.rs
After breaking the fuzzy matcher out into its own file (it's stand alone, so doing so helps make `tester.rs` feel a little less intimidating), this fixes a bug in the current fuzzy matcher (https://github.com/softdevteam/lang_tester/commit/c9317f508e6ad0c50bfb553060f663fdd960312f) and then allows `...` to be used at the start and/or end of the line (https://github.com/softdevteam/lang_tester/commit/65d39d86b249b5fbb43dfb1d8f51549275c64076). This doesn't hugely affect code complexity, but does make it easier to think about from an end-user's perspective IMHO>
=> Better fuzzy matching

Cargo.toml, README.md, src/lib.rs, src/tester.rs
This means that doing things like:
```
cargo test a
```
only runs tests with "a" in their name.
Since this feature has to read command-line parameters, which might not be appropriate in all places, it can be switched off by specifying `use_cmdline_args(false)` (the default is `true`).
=> Allow the user to specify which tests they want to run on the command line

Cargo.toml, src/fuzzy.rs, src/parser.rs, src/tester.rs
This makes `lang_tester` run tests in parallel (one job per CPU core). This seriously speeds things up -- yksom's tiny test suite of 6 language tests by over 2x on my 2 core laptop with hyper-threading on (and a mere ~1.8x with hyper-threading off).
https://github.com/softdevteam/lang_tester/commit/9cc27f7abbeab154d09af9b911bb701944cbf828 does the parallelisation in a simple but effective way. https://github.com/softdevteam/lang_tester/commit/da955eef58bb34de2399f764f73434551a1dded6 and https://github.com/softdevteam/lang_tester/commit/2e1dbe66dd3661f3b5fbdae72237cceb44031d8e are semi-mechanical commits which prepare the ground for doing "full and proper" parallisation in https://github.com/softdevteam/lang_tester/commit/6159172091ea9c0d97d9cac97ec3b65da73ed72e.
=> Parallel tests

src/fuzzy.rs, src/lib.rs, src/parser.rs, src/tester.rs
The problem with running things multi-threaded is that a panic in one thread doesn't kill the others, so the user can easily end up not noticing that something very bad has happened. This commit turns panics into process-exiting fatal errors: when something bad happens, it's now very hard not to notice it!
=> Exit the process on a fatal error.

src/tester.rs
If we have several tests:
```
A:
stdout: ...
B:
stdout: ...
```
then if test A failed, we want to stop immediately, otherwise test B might still succeed and lead to confusion. In other words, stop on the first error, and print the output of that error to the user.
Most of this PR is a couple of comments to clarify the situation, but the newly added `break` is critical!
=> Bail out as soon as a test has failed.

src/tester.rs
This is modelled after the same functionality in `cargo test`.
=> Add support for altering the number of test threads

Cargo.toml, src/tester.rs
This commit prints a warning to stderr every multiple of `TIMEOUT` seconds that a given test has not completed. This is subtly different to cargo, which only prints a warning after `TIMEOUT` has been exceeded once (if something's very slow, for debugging reasons it can sometimes be nice to know *how* slow).
This is particularly useful when running parallel tests when it is often not obvious why the test runner has not completed. This is similar to how `cargo test` works.
=> Warn users when a test has exceeded a timeout.

README.md, examples/rust_lang_tester/run_tests.rs, src/lib.rs, src/parser.rs, src/tester.rs
This was previously a mess, with the term "test" heavily overloaded. This commit tidies that up somewhat. Test files contain test data. Test data contains test commands. Test commands contain sub-tests. Perfect? No -- but definitely better than what came before.
=> Get the terminology into some sort of order.

src/tester.rs
Without this, newer rustc's complain about bare trait objects.
=> Use the dyn keyword where possible.

src/fuzzy.rs, src/parser.rs
We stated this as an invariant for fuzzy::match_vec but the code that should have enforced it didn't work properly. Mea culpa!
As well as fixing this (with, perhaps inevitably, simpler code than the buggy code it replaces!), this commit adds asserts to stop this ever happening again.
=> Really delete blank lines.

README.md
This wasn't documented anywhere and I took it from `yksom`.
=> Add instuctions to README for using with cargo test

examples/rust_lang_tester/lang_tests/custom_cla.rs, src/parser.rs, src/tester.rs
Sometimes it's desirable to run certain tests (or subcommands) with custom command line arguments. This commit adds the ability to do this without the need for defining a separate test harness.
We introduce a new keyword, `args`, which can be optionally specified for each test command. For example, suppose an individual test relied on handling some user input, one could pass this input as follows:
```
Run-time:
args: 1234
status: success
```
This passes the command line argument 1234 to the command named "Run-time". Note that command line arguments are always passed as strings.
It is important to remember that custom arguments should not break invariants which are relied upon by the test runner. For example, suppose a test runner has two commands: compile, and then execute a C program. If …
=> Add ability to pass per test command line args

README.md, examples/rust_lang_tester/lang_tests/custom_cla.rs, examples/rust_lang_tester/lang_tests/unused_var.rs, src/fuzzy.rs, src/lib.rs, src/parser.rs, src/tester.rs
This PR embraces the new era of lang_tester using defaults to simplify the code base. The motivation is contained in the doc changes of https://github.com/softdevteam/lang_tester/commit/e13d06647235906f28e92a05dce8c2acf674fa3b, with the code then being easily simplified (in a way that's semantically backwards compatible, though note that it does change the output shown to users when tests fail) in https://github.com/softdevteam/lang_tester/commit/dc4e11c14926dffdc790afa5253d5a26d417791a. This PR deletes more code than it adds! Please test, though, on your own code to check that it doesn't do anything silly!
=> Explicitly use defaults

Cargo.toml, examples/rust_lang_tester/lang_tests/unused_var.rs, src/tester.rs
This adds support for `--nocapture` to lang_tester. The main part of the PR is https://github.com/softdevteam/lang_tester/commit/d0ac369a66d84c3f246c1e7c8d0706456a1b1023. As with normal `cargo test`, `--nocapture` on its own tends to lead to baffling interleaving of commands: it generally pairs well with `--test-threads=1`.
=> Add support for --nocapture

src/tester.rs
The extra `'` characters had crept in during testing and I didn't notice them when making a previous PR. Mea culpa!
=> Remmove quotes from output.

examples/rust_lang_tester/lang_tests/sig_caught.rs, src/parser.rs, src/tester.rs
If the user expects a command, `x`, to terminate due to a signal being
thrown, they can now specify this explicitly, rather than using the
generic "error" status.
A test will still pass if it expects an "error" status from `x` which
terminated with a signal, as "error" is a superset of "signal".
=> Add status for specifying that a signal was caught

README.md, examples/rust_lang_tester/lang_tests/ignore.rs, src/lib.rs, src/parser.rs, src/tester.rs
Sometimes we might want to add tests that we can't yet run successfully, so being able to ignore them can be useful.
=> Ignorable tests

src/tester.rs
The basic problem is that Rust allows move closure to capture variables if they
have a `Copy`able type, leading to the "outer" and "inner" variables to diverge.
For example, this simple program:
```
fn main() {
let mut x = 0;
let mut y = move |z: u32| {
x += z;
println!("inner x {}", x);
};
println!("outer x {}", x);
y(2);
println!("outer x {}", x);
}
```
outputs:
```
outer x 0
inner x 2
outer x 0
```
Note that the above program gives no warnings (or errors) in rustc or clippy.
In this case, the `num_ignored` variable had started life in single-threaded
code and later been moved to multi-threaded code. It compiled, even though the
outer variable could never be mutated. In other words, lang_tester always said
that 0 tests were ignored -- even if some were ignored!
This commit fixes this …
=> Fix bug where the outer `num_ignored` variable was ignored.

src/tester.rs
This function allows the user to specify the default number of test threads ahead of time. This is useful if, for example, a test harness will only work in a single threaded context, since lang_tester attempts to parallelise by default.
It's a draft PR for now as I want to check if you're happy with the API. If so I'll add some docs for it and update it.
=> Add function to specify number of test threads

.buildbot.sh, examples/rust_lang_tester/lang_tests/nested/test.rs, examples/rust_lang_tester/lang_tests/no_main.rs, src/tester.rs
Although I'd never tried it, lang_tester supported nested tests (i.e. tests in nested directories). However, if you had something like:
```
lang_tests/
a.rs
b/
c.rs
```
then the output would be:
```
lang_tests::a.rs
lang_tests::c.rs
```
That seems OK until you do this:
```
lang_tests/
a.rs
b/
a.rs
```
and then the output would be:
```
lang_tests::a.rs
lang_tests::a.rs
```
Which test is which?
This commit makes it so that nested tests print out their directory name(s):
```
lang_tests::a.rs
lang_tests::b::a.rs
```
This does rely on path canonicalisation, which is never entirely guaranteed to succeed, so there is a fallback mechanism if it fails.
=> Print out the name of nested tests in a more pleasing way

.buildbot.sh, Cargo.toml, examples/fm_options/lang_tests/nondeterministic.py, examples/fm_options/lang_tests/simple.py, examples/fm_options/run_tests.rs, src/tester.rs
This allows lang_tester users to e.g. use name matching in their tests.
I'm not sure if this is the right API or not: it's flexible but that brings some complexity as well. We could, for example, pass a boolean `is_stderr`, but that would restrict us forever more to just stderr/stdout tests. Maybe that's all we need, but I'm not sure.
=> Add the ability to override fm's defaults when using lang_tester.

Cargo.toml, README.md, examples/fm_options/lang_tests/echo.py, examples/fm_options/run_tests.rs, examples/rust_lang_tester/lang_tests/echo_multiline.rs, src/lib.rs, src/parser.rs
This allows us to write things such as:
```
x:
a
b
c
```
and differentiate the leading whitespace in the lines. Trailing whitespace is always stripped. Note that this change is backwards compatible because `fm` defaults to whitespace-insensitive matching, so unless users explicitly request whitespace-sensitive matching they won't know the difference.
This fixes https://github.com/softdevteam/lang_tester/issues/65 in a simpler way than I think we originally thought possible.
=> Don't strip leading whitespace from lines.

Cargo.toml, src/tester.rs
If an fm match fails, this commit uses the output from fm rather than printing
the raw stdout/stderr. For example, with the upcoming context support in fm,
this leads to the helpful output such as the following:
```
---- lang_tests::nested_backtrace2.som stderr ----
Pattern (error at line 3):
|Traceback (most recent call at bottom):
|  ...
>> |  ...nested_backtrace2.som, line 30, column 12:
|      run = ( self m )
|  ...nested_backtrace2.som, line 26, column 8:
|          1 == 0
...
Text (error at line 28):
...
|          self ifFalse: [ ^falseBlock value ].
|  File /home/ltratt/yksom/lang_tests/nested_backtrace2.som, line 29, column 21:
|            ifFalse: [ 2 / 0 ].
>> |Division by zero.
```
This makes it much easier to understand why a test failed. Previously I had
sometimes spent …
=> Display errors as fm output.

CHANGES.md, Cargo.toml
Since we expose `fm` directly to the user, the bump in its interface requires us to bump `lang_tester`'s version to 0.4.0.
=> Prepare a 0.4.0 release.

CHANGES.md, README.md, examples/fm_options/run_tests.rs, examples/rust_lang_tester/run_tests.rs, src/lib.rs, src/tester.rs
lang_tester tries to make it as easy as possible to set-up, so it has a fairly simple API. One way I did that was by passing the contents of a file to a `test_extract` function. However, that is fairly inflexible, and also it turns out not very much simpler (it doesn't help that `test_extract` returns `Option<String>`: frankly, it's easier for tests to panic in such situations).
This commit therefore changes the `test_extract` function signature from:
```
Fn(&str) -> Option<String> + Send + Sync,
```
to:
```
Fn(&Path) -> String + Send + Sync,
```
In other words, users now have to a) read the contents of a path themselves (but
it doesn't necessarily have to be the path passed to the function!) b) return a
`String` rather than an `Option<String>`.
In practise, most `test_extract` functions …
=> Make test_extract take `&Path`s rather than `&str`s.

README.md, examples/rust_lang_tester/run_tests.rs, src/lib.rs
This PR tries to clarify the documentation somewhat. The problem with `lang_tester` is that it's so brutally simple that there's a tendency to assume that it can't possibly be *that* simple. I've tried to bring out a few of the concepts more explicitly to emphasise the fundamentals a bit better. This will probably never be perfect, but anything which makes it better can only be a good thing.
=> Try to get some of the concepts across more clearly in the docs

CHANGES.md, Cargo.toml, src/tester.rs
0.6.0 had a nasty bug whereby file filtering didn't work. I've yanked that from crates.io but we should prepare a correct version ASAP.
=> Prepare a 0.6.1 release

src/tester.rs
Previously this rendered in HTML with the full URL spelt out -- which isn't very helpful!
=> Fix formatting.

README.md, examples/rust_lang_tester/lang_tests/custom_cla.rs, src/lib.rs, src/parser.rs
The `extra-args` option is useful, but the documentation was misleading (https://github.com/softdevteam/lang_tester/commit/d014d43fb0f184746a37abb75af41b398e197fef) and indeed the very name of the key is misleading (https://github.com/softdevteam/lang_tester/commit/099096cb9936957be6d306d76593f9bf639775fa). The latter is a backwards incompatible change, but since I had to look at the source code to work out what's going on, it's hard to believe that many other people would be able to use this option correctly given it's currently-misleading name.
=> Fix docs for, and rename, 'extra_arg'

src/tester.rs
This should fix the issue seen by @vext01 in https://github.com/ykjit/yk/pull/447#issuecomment-987812395.
=> Explicitly fail if FMBuilder doesn't succeed.

Cargo.toml, lang_tests/rerun/lang_tests/rerun_status.py, lang_tests/rerun/lang_tests/rerun_stderr.py, lang_tests/rerun/lang_tests/rerun_stdout.py, lang_tests/rerun/main.rs, src/parser.rs, src/tester.rs
This PR adds support for rerunning tests if a) the test fails b) at least one of `rerun-if-{status, stderr, stdout}` matches.
Consider this test (which is included in the PR):
```python
import os, sys
cookie = os.path.join(os.environ["CARGO_MANIFEST_DIR"], "target", "tmp", "rerun_status_cookie")
i = 0
if os.path.exists(cookie):
i = int(open(cookie, "r").read().strip()) + 1
if i == 5:
sys.exit(0)
open(cookie, "w").write(str(i))
sys.exit(42)
```
The first 4 times this test runs it will return with exit code 42, causing the test to be rerun. On the 5th time it will return with exit code 0.
The default number of times to rerun tests is arbitrarily set at 3, but users can override this.
Note that I have vaccillated several times over how to define this feature. At one point I thought it should …
=> Add rerun-if-{status, stderr, stdout}

src/tester.rs
Previously we just filtered on the leaf, so if you had multiple tests with the same leaf but in different directories, you could not filter them individually.
Fixes https://github.com/softdevteam/lang_tester/issues/110 (or hopefully does! @vext01 does this work for you?).
=> Use the full test name (e.g. `a::b::c`) when filtering.

examples/rust_lang_tester/lang_tests/ignore.rs, examples/rust_lang_tester/lang_tests/not_ignore.rs, examples/rust_lang_tester/run_tests.rs, src/lib.rs, src/parser.rs, src/tester.rs
This PR's main aim is to remove `ignore` and add `ignore-if: <cmd>` which allows a test to flexibly specify when it should/shouldn't be ignored (https://github.com/softdevteam/lang_tester/commit/9ffa2b2f02c8f51de722bcc5b64c8c9ad642729a). However, this means that the ability to specify a human string for *why* a test is ignored is lost so this PR also adds the ability to allow comment lines (https://github.com/softdevteam/lang_tester/commit/d09c0dc05a59dd7fb9cb58ab68fe8f2485ad5bd9).
My guess is that the main way this will be used is with `test` so you might have things like `ignore-if: test $YKB_TRACER == "swt"` or `ignore-if: test $YKB_TRACER != "swt"` and so on. @Pavel-Durov does this allow you to specify tests in your yk PR in the way you need?
This is a breaking change, so if we do …
=> Replace `ignore` with `ignore-if`.

README.md, src/lib.rs
The example code in both `lib.rs` and `README.md` is both slightly out-of-date and slightly confusing. This PR fixes a few obvious issues.
=> Fix example

src/parser.rs
Previously this was, incorrectly, "last ignore-if in the file" wins, which was a great way of hiding bugs.
=> Raise an error if `ignore-if` is specified more than once.
